=== teodora12/BSEP-master/Backend-agent/src/main/java/com/ftn/agent/model/Address.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/address" xmlns:addr="http://www.ftn.uns.ac.rs/address">
    <xs:element name="Address">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id" type="xs:long"/>
                <xs:element name="Country" type="xs:string"/>
                <xs:element name="City" type="xs:string"/>
                <xs:element name="Street" type="xs:string"/>
                <xs:element name="StreetNumber" type="xs:string"/>
                <xs:element name="Longitude" type="xs:double"/>
                <xs:element name="Latitude" type="xs:double"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== teodora12/BSEP-master/Backend/src/main/resources/address.xml
<?xml version="1.0" encoding="UTF-8"?>
<Address xmlns="http://www.ftn.uns.ac.rs/address"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/address file:/C:/Users/Dell/Desktop/xxxx/Address.xsd">
    <Id>-1073741773</Id>
    <Country>Country0</Country>
    <City>City0</City>
    <Street>Street0</Street>
    <StreetNumber>StreetNumber0</StreetNumber>
    <Longitude>0</Longitude>
    <Latitude>0</Latitude>
</Address>
